#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Blowski\ConsoleCommands\CrawlCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$command = new CrawlCommand();
$application->add($command);

$application->run();