#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Blowski\CrawlCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new CrawlCommand());
$application->run();